[package]
name = "derives"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.72"
quote = "1.0.33"
syn = { version = "2.0.43", features = ["full"] }
